### ISSUE TITLE
Issue with diamond_eyes.py

### ISSUE THREAD

**Issue by 0dayCTF** [guyinatuxedo/remenissions#3]
```
[+] Starting local process '/usr/bin/gdb': pid 95289
Traceback (most recent call last):
  File "/root/tools/remenissions/diamond_eyes.py", line 1314, in <module>
    dynamic_analyzer.setup()
  File "/root/tools/remenissions/diamond_eyes.py", line 708, in setup
    self.get_architecture()
  File "/root/tools/remenissions/diamond_eyes.py", line 972, in get_architecture
    parsed_output = output.split(b"architecture is set automatically ")[1].split(b"\n")[0]
IndexError: list index out of range

```
GDB Version:
gdb (Debian 10.1-1.7) 10.1.90.20210103-git

GEF Output in GDB:
gef➤  show architecture
The target architecture is set to "auto" (currently "i386").

**Comment by MaximeFrancoeur** [comment]
have same problem, but I don't use /root/ with Kali 2021, any news about this?

**Comment by guyinatuxedo** [comment]
I would recommend either running it in Ubuntu, or trying to use the vm
mentioned in the readme. Ask in the nightmare discord for further questions.
